spring:
  threads:
    virtual:
      enabled: true
  application:
    name: Hostfully Booking API
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: ${SPRING_DATASOURCE_PASSWORD:org.postgresql.Driver}
  h2:
    console.enabled: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace